/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package letv.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 07-14-2014
 * 
 * XDoclet definition:
 * @struts.form name="add_albumsForm"
 */
public class Add_albumsForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** selected_ids property */
	private String []selected_ids;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the selected_ids.
	 * @return String
	 */
	public String[] getSelected_ids() {
		return selected_ids;
	}

	/** 
	 * Set the selected_ids.
	 * @param selected_ids The selected_ids to set
	 */
	public void setSelected_ids(String [] selected_ids) {
		this.selected_ids = selected_ids;
	}
}