/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package letv.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import letv.struts.form.Add_albumsForm;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 07-14-2014
 * 
 * XDoclet definition:
 * @struts.action path="/add_albums" name="add_albumsForm" input="/form/select_albums.jsp" scope="request" validate="true"
 * @struts.action-forward name="selected_failed" path="/form/select_albums.jsp"
 * @struts.action-forward name="selected_ok" path="/admin/publish_albums.jsp"
 */
public class Add_albumsAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		Add_albumsForm opf = (Add_albumsForm) form;// TODO Auto-generated method stub
		String[] alblis = opf.getSelected_ids();
		if (alblis == null || alblis.length == 0) {
			return mapping.findForward("selected_failed");
		}
		if (letv.mock.album.AlbumOper.saveSelectedAlbums(alblis, true)) {
			return mapping.findForward("selected_ok");
		} else {
			return mapping.findForward("selected_failed");			
		}	
		
	}
}