/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package letv.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 07-15-2014
 * 
 * XDoclet definition:
 * @struts.form name="publish_albForm"
 */
public class Publish_albForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** albumid property */
	private String []albumid;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the albumid.
	 * @return String
	 */
	public String []getAlbumid() {
		return albumid;
	}

	/** 
	 * Set the albumid.
	 * @param albumid The albumid to set
	 */
	public void setAlbumid(String []albumid) {
		this.albumid = albumid;
	}
}