/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package letv.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 07-14-2014
 * 
 * XDoclet definition:
 * @struts.form name="select_ablumsForm"
 */
public class Select_ablumsForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** alb_type property */
	private String alb_type;

	/** alb_name property */
	private String alb_name;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the alb_type.
	 * @return String
	 */
	public String getAlb_type() {
		return alb_type;
	}

	/** 
	 * Set the alb_type.
	 * @param alb_type The alb_type to set
	 */
	public void setAlb_type(String alb_type) {
		this.alb_type = alb_type;
	}

	/** 
	 * Returns the alb_name.
	 * @return String
	 */
	public String getAlb_name() {
		return alb_name;
	}

	/** 
	 * Set the alb_name.
	 * @param alb_name The alb_name to set
	 */
	public void setAlb_name(String alb_name) {
		this.alb_name = alb_name;
	}
}