#
# Autogenerated by Thrift Compiler (0.9.1)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException

from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None


class FilterStatus:
  BLOOM_EXIST = 1
  BLOOM_NOT_EXIST = 2
  BLOOM_ERROR = 10

  _VALUES_TO_NAMES = {
    1: "BLOOM_EXIST",
    2: "BLOOM_NOT_EXIST",
    10: "BLOOM_ERROR",
  }

  _NAMES_TO_VALUES = {
    "BLOOM_EXIST": 1,
    "BLOOM_NOT_EXIST": 2,
    "BLOOM_ERROR": 10,
  }

