/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package letv.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import letv.struts.form.Publish_albForm;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;

/**
 * MyEclipse Struts Creation date: 07-15-2014
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/publish_alb" name="publish_albForm"
 *                input="/admin/publish_albums.jsp" scope="request"
 *                validate="true"
 * @struts.action-forward name="pubulish_status"
 *                        path="/admin/publish_albums.jsp"
 */
public class Publish_albAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		Publish_albForm fis = (Publish_albForm) form;// TODO Auto-generated
														// method stub
		String[] pbaids = fis.getAlbumid();
		ActionMessages ams = new ActionMessages();
		if (pbaids == null) {
			ams.add("publish_errors",
					new ActionMessage("everything.logic.fail"));
			saveErrors(request, ams);
		} else {
			System.out.println("print result");
			if (!letv.mock.album.AlbumOper.saveSelectedAlbums(pbaids, false)) {
				System.out.println("Failed To Save Selected Albums");
				ams.add("publish_errors", new ActionMessage(
						"everything.logic.fail"));
			} else {
				if (!letv.mock.album.AlbumOper.get_instance().send_top_result()) {
					System.out.println("Failed send info to remote host");
					ams.add("publish_errors", new ActionMessage(
							"everything.logic.fail"));
				} else {
					System.out.println("Success send info to remote host");
					ams.add("publish_errors", new ActionMessage(
							"everything.logic.ok"));
				}
			}
			
		}
		saveErrors(request, ams);
		return mapping.findForward("pubulish_status");
	}
}