/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package letv.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import letv.struts.form.Select_ablumsForm;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 07-14-2014
 * 
 * XDoclet definition:
 * @struts.action path="/select_ablums" name="select_ablumsForm" input="/form/select_ablums.jsp" scope="request" validate="true"
 * @struts.action-forward name="ok_fwd" path="/form/usrlogin.jsp"
 * @struts.action-forward name="failed_fwd" path="/form/usrlogin.jsp"
 */
public class Select_ablumsAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		Select_ablumsForm slf = (Select_ablumsForm) form;// TODO Auto-generated method stub
		//letv.mock.album.AlbumOper oper = new letv.mock.album.AlbumOper();		
		return null;
	}
}